name: Build and Deploy

on:
  push:
    branches:
      - main  # 你可以根据需要更改分支

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # 获取最近两次提交，以便比较变化

      - name: Detect changed packages
        id: changed-packages
        run: |
          # 检测哪些 package 发生了变化
          if git rev-parse --verify HEAD^ > /dev/null 2>&1; then
            CHANGED_PACKAGES=$(git diff --name-only HEAD^ HEAD | grep -o 'packages/[^/]*' | sort | uniq)
          else
            CHANGED_PACKAGES=$(git ls-tree -r HEAD --name-only | grep -o 'packages/[^/]*' | sort | uniq)
          fi
          echo "Changed packages: $CHANGED_PACKAGES"
          echo "packages=$CHANGED_PACKAGES" >> $GITHUB_OUTPUT

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16  # 你可以根据需要更改 Node.js 版本

      - name: Build and deploy changed packages
        run: |
          # 遍历所有发生变化的 packages
          for package in ${{ steps.changed-packages.outputs.packages }}; do
            if [[ "$package" == "packages/entry" || "$package" == "packages/demo1" || "$package" == "packages/demo2" ]]; then
              echo "Building and deploying $package"
              cd $package
              npm install
              npm run build
              echo "====Build completed.===="
              pwd
              ls
              # 部署到 GitHub Pages
              PUBLISH_DIR=$(basename $package)
              mkdir -p ../../dist/$PUBLISH_DIR
              cp -r dist/* ../../dist/$PUBLISH_DIR
              echo "====Copied.===="
              cd ../../
              pwd
              ls
            fi
          done

      - name: Deploy to GitHub Pages
        if: ${{ steps.changed-packages.outputs.packages != '' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          keep_files: true  # 保留之前构建的文件
